[package]
authors  = ["Jerónimo Sánchez <jeronimosg@hotmail.es>"]
edition  = "2018"
license  = "MIT"
name     = "gpgpu"
resolver = "2"
version  = "0.0.0"

[dependencies]
bytemuck = "1.7"
futures  = { version = "0.3", default-features = false, features = ["executor"] }
log      = "0.4"
wgpu     = { version = "0.10", features = ["spirv"] }
