[package]
authors     = ["Jerónimo Sánchez <jeronimosg@hotmail.es>"]
categories  = ["concurrency", "science"]
description = "Simple WIP GPGPU framework built on top of wgpu"
edition     = "2018"
exclude     = ["examples"]
keywords    = ["gpgpu", "compute", "opencl", "cuda"]
license     = "MIT"
name        = "gpgpu"
repository  = "https://www.github.com/UpsettingBoy/gpgpu-rs"
resolver    = "2"
version     = "0.0.0"

[dependencies]
bytemuck = "1.7"
futures  = { version = "0.3", default-features = false, features = ["executor"] }
log      = "0.4"
wgpu     = { version = "0.10", features = ["spirv"] }
